### ISSUE TITLE
Presence of a `time` executable assumed

### ISSUE THREAD

**Issue by chrysn** [cabo/kdwatch#2]
On systems without a `time` binary, refreshes do trigger but keep showing the old file as it can't be rebuilt.

Removing the `ENV["KDRFC_PREPEND"] = "time"` line resolves the issue; this can be viable fix if that command was only there for benchmarking purposes.

(`time` is part of POSIX, but on some systems it is implemented as a shell built-in).

**Comment by cabo** [comment]
The "time" calls actually provide a useful progress indicator, as well, so I'd prefer to leave them in.  Fixed in 0.4.1.
